version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.psql
    environment:
      POSTGRES_USER: "worker1"
      POSTGRES_PASSWORD: "worker1_pw"
      POSTGRES_DB: "birthday"
    ports: ["5432:5432"]

  test:
    build:
      context: .
      dockerfile: Dockerfile.ci
    environment:
      POSTGRES_USER: "worker1"
      POSTGRES_PASSWORD: "worker1_pw"
      POSTGRES_DB: "birthday"
      APP_DB_HOST: "192.168.99.100"
    network_mode: "service:postgres"
    depends_on:
      - postgres

