FROM alpine

ENV KUBE_LATEST_VERSION="v1.8.3"
ENV HELM_VERSION="v2.7.0"
# access credentials for created cluster
ENV KUBECONFIG=/root/.kube/admin.conf
ENV FILENAME="helm-${HELM_VERSION}-linux-amd64.tar.gz"

RUN apk add --update ca-certificates \
    && apk add --update -t deps curl \
    && apk add bash \
    && apk add --no-cache curl bind-tools \
    && apk add git \
    && curl -L https://storage.googleapis.com/kubernetes-release/release/${KUBE_LATEST_VERSION}/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl \
    && chmod +x /usr/local/bin/kubectl \
    && curl -L http://storage.googleapis.com/kubernetes-helm/${FILENAME} -o /tmp/${FILENAME} \
    && tar -zxvf /tmp/${FILENAME} -C /tmp \
    && mv /tmp/linux-amd64/helm /bin/helm \
    # Cleanup uncessary files
    && apk del --purge deps \
    && rm /var/cache/apk/* \
    && rm -rf /tmp/*

ADD Charts/production-deploy /root/production-deploy

ADD admin.conf /root/.kube/admin.conf

RUN helm init

WORKDIR /

CMD bash
